frontend/controllers/RecipeController.php
<?php
/**
 * Created by PhpStorm.
 * User: DRM
 * Date: 21.01.2016
 * Time: 11:18
 */

namespace frontend\controllers;


use backend\recipe\models\RecipeIngredients;
use backend\recipe\models\RecipeRel;
use frontend\models\SearchRecipe;
use Yii;
use yii\web\Controller;
use backend\models\Lang;
use common\models\Func;
use backend\recipe\models\Recipe;
use yii\data\Pagination;
use backend\ingredients\models\Ingredients;
use yii\helpers\Url;

class RecipeController extends Controller
{

    public $recipes;
    public $lang;
    public $recipe_rel;
    public $recipe_content;

    public function init()
    {
        $this->lang = Lang::getCurrent()->url;
        $this->recipes = new Recipe();
        $this->recipe_rel = new RecipeRel();
        $this->recipe_content = new RecipeIngredients();
    }

    public function actionIndex($id=null)
    {
//        $recent = $this->recipes->findRecentModel($this->lang);
        if($id != null){
            $cats = $this->recipe_rel->catFilter($id);
            $category = [];
            foreach ($cats as $cat) {
                array_push($category,$cat->item_id);
            }
            $model = $this->recipes->findModelCat($category);
        }else{
            $model = $this->findModel();
        }
        $countQuery = clone $model;
        $pages = new Pagination(['totalCount' => $countQuery->count(),'defaultPageSize'=>6]);
        $models = $model->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index',[
            'models' => $models,
            'pages' => $pages,
//            'recent' => $recent
        ]);
    }

    public function actionView($id)
    {
        $model = $this->recipes->find()->where(['parrent_id'=>$id, 'lang'=>$this->lang])->one();

        return $this->render('view',[
            'model' => $model,
//            'recent' => $recent
        ]);
    }

    public function actionSearch(){

        $model = new SearchRecipe();

        if ($model->load(Yii::$app->request->post())) {
//            Func::d($model);
            $model = $model->search($model->keyword);
            $countQuery = clone $model;
            $pages = new Pagination(['totalCount' => $countQuery->count(),'defaultPageSize'=>6]);
            $models = $model->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

            return $this->render('index',[
                'models' => $models,
                'pages' => $pages,
//            'recent' => $recent
            ]);
        }

    }

    public function findModel()
    {
        $model = $this->recipes->find()->where(['lang' => $this->lang]);
        return $model;
    }

    public static function getProducts($id,$lang)
    {
        $ingredients = new RecipeIngredients();
        $ingredient = $ingredients->getAllCats($id);
        $ing = new Ingredients();
        $title = 'title_'.$lang;
        $result = '';
        $i=1;
//        Func::d($ingredient);
        foreach ($ingredient as $item){
            $product = $ing->recipeIngredient($item->ingredient_id,$lang);
            if($item->ingredient_id != null)
            {
                $result .= '<p><span class="ingredients">' . $i . '</span><a href="'. Url::to(['product/view', 'id' => $item->ingredient_id, 's' => $product->slug]) .'">'.$product->title.'</a>&nbsp;' . $item->count .'</p>';
            }else{
                $result .= '<p><span class="ingredients">' . $i . '</span>'.$item->$title.'</p>';
            }
            $i++;
        }

        return $result;
    }

}

frontend/views/recipe/index.php
<?php

use yii\widgets\LinkPager;
use yii\helpers\Url;
use yii\helpers\Html;
use common\models\Func;
use backend\models\Lang;

$this->title = 'Recipes';

?>
        <div class="top_panel_title top_panel_style_1  title_present breadcrumbs_present scheme_original">
            <div class="top_panel_title_inner top_panel_inner_style_1  title_present_inner breadcrumbs_present_inner">
                <div class="content_wrap">
                    <h1 class="page_title"><?= Yii::t('file','menu-recipes');?></h1>
                </div>
            </div>
        </div>

        <div class="page_content_wrap archive category category-masonry category-6 origano_body body_style_wide body_filled theme_skin_origano article_style_stretch layout_masonry_2 template_masonry top_panel_show top_panel_above sidebar_show sidebar_right sidebar_outer_hide mmm mega_main_menu-2-0-7 wpb-js-composer js-comp-ver-4.7.4 vc_responsive top_panel_fixed">

            <div class="content_wrap">
                <div class="content">
                    <div class="isotope_wrap inited" data-columns="2" style="position: relative;">
                        <?php foreach($models as $model): ?>
                        <div class="isotope_item isotope_item_masonry isotope_item_masonry_2 isotope_column_2 isotope_item_show fl" style="opacity: 1; ">
                            <article class="post_item post_item_masonry post_item_masonry_2 post_format_standard odd">

                                <h5 class="post_title"><a href="<?= Url::to(['recipe/view', 'id' => $model->parrent_id, 's' => $model->slug]) ?>"><?= $model->title ?></a></h5>
                                <div class="sc_line sc_line_style_solid" style="border-top-style:solid;"></div>

                                <div class="post_featured">
                                    <a class="hover_icon hover_icon_link" href="<?= Url::to(['recipe/view', 'id' => $model->parrent_id, 's' => $model->slug]) ?>">
                                        <?php if(!empty($model->img)) {?>
                                        <div class="recipe-post_thumb" data-image="<?= Url::to('/backend/web/upload/recipe/thumbs/'.$model->img);?>" style="background-image: url( <?php echo Url::to('/backend/web/upload/recipe/thumbs/'.$model->img);?>);" data-title="">

                                        </div>
                                        <?php }else{ ?>
                                        <div class="recipe-post_thumb" data-image="<?= Url::to('/frontend/web/image/images.png');?>" style="background-image: url( <?php echo Url::to('/backend/web/upload/recipe/thumbs/'.$model->img);?>);" data-title="">

                                        </div>
                                        <?php } ?>
                                    </a>
                                </div>

                                <div class="post_content isotope_item_content">

                                    <div class="post_descr">
                                        <p><?= Func::getExcerpt($model->description,0,100) ?></p><a href="<?= Url::to(['recipe/view', 'id' => $model->parrent_id, 's' => $model->slug]) ?>" class="post_readmore sc_button sc_button_square sc_button_style_filled sc_button_bg_link sc_button_size_medium"><span class="post_readmore_label"><?= Yii::t('file','view');?></span></a>
                                    </div>
                                </div>
                                <!-- /.post_content -->
                            </article>
                            <!-- /.post_item -->
                        </div>
                        <?php endforeach; ?>
                        <?php
                        echo LinkPager::widget([
                            'pagination' => $pages,
                        ]);
                        ?>
                    </div>
                    <!-- /.isotope_wrap -->

                </div>
                <!-- </div> class="content"> -->
                <?php $this->beginContent('@app/views/layouts/sidebar-recipe.php'); ?>


                <?php $this->endContent(); ?>

            </div>
            <!-- </div> class="content_wrap"> -->
        </div>
        <!-- </.page_content_wrap> -->

frontend/views/recipe/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Recipes | '.$model->title;

?>

        <div class="top_panel_title top_panel_style_1  title_present breadcrumbs_present scheme_original">
            <div class="top_panel_title_inner top_panel_inner_style_1  title_present_inner breadcrumbs_present_inner">
                <div class="content_wrap">
                    <h1 class="page_title"><?= $model->title ?></h1>
                </div>
            </div>
        </div>

        <div class="page_content_wrap single single-post postid-1044 single-format-standard origano_body body_style_wide body_filled theme_skin_origano article_style_stretch layout_single-standard template_single-standard top_panel_show top_panel_above sidebar_show sidebar_right sidebar_outer_hide mmm mega_main_menu-2-0-7 wpb-js-composer js-comp-ver-4.7.4 vc_responsive top_panel_fixed">

            <div class="content_wrap">
                <div class="content">
                    <article class="itemscope post_item post_item_single post_featured_default post_format_standard post-1044 post type-post status-publish format-standard has-post-thumbnail hentry category-masonry category-portfolio tag-tag2 tag-tag3 tag-tag1 tag-portfolio tag-video" itemscope="" itemtype="http://schema.org/Review">
                        <section class="post_featured">
                            <div class="post_thumb recipe-info" data-image="<?= Url::to('/backend/web/upload/recipe/thumbs/'.$model->img);?>" data-title="Organic Farming Feeds the World">
                                <?php if(!empty($model->img)){ ?>
                                <a id="recipe-thumb" class="hover_icon hover_icon_view inited tumbnail-recipe fl" href="<?= Url::to('/backend/web/upload/recipe/'.$model->img);?>">
                                    <?= Html::img('/backend/web/upload/recipe/thumbs/'.$model->img);?>
                                </a>
                                <?php }else{
                                    echo Html::img('/frontend/web/image/images.png');
                                } ?>
                                <div class="ingredient-block">
                                    <h3><?= Yii::t('file','ingredients');?></h3>
                                    <?= \frontend\controllers\RecipeController::getProducts($model->parrent_id,\backend\models\Lang::getCurrent()->url) ?>
                                </div>
                                <?php $gallery = \common\models\Func::getGallery("recipe/".$model->parrent_id.'/thumbs'); ?>
                                <!--                                --><?php //\common\models\Func::d($gallery); ?>
                                <?php if($gallery){ ?>
                                    <!--                                --><?php //\common\models\Func::d("a") ?>
                                    <div class="small-gallery-recipe" id="thumbnails">
                                        <?php foreach($gallery as $one){ ?>
                                            <a class="inline" href="<?= Url::to('/backend/web/upload/recipe/'.$model->parrent_id.'/'.$one)?>">
                                                <img class="img" src="<?= Url::to('/backend/web/upload/recipe/'.$model->parrent_id.'/thumbs/'.$one) ?>" data-url = "<?= Url::to('/backend/web/upload/ingredients/'.$model->parrent_id.'/'.$one)?>"/>
                                            </a>
                                        <?php }?>
                                    </div>
                                <?php }?>
                            </div>
                        </section>


                        <section class="post_content" itemprop="reviewBody">
                            <h1 itemprop="name" class="product_title entry-title"><?= Yii::t('file','recipe-description');?></h1>
                            <p><?= $model->description ?></p>
                        </section>
                        <!-- </section> class="post_content" itemprop="reviewBody"> -->

                    </article>
                    <!-- </article> class="itemscope post_item post_item_single post_featured_default post_format_standard post-1044 post type-post status-publish format-standard has-post-thumbnail hentry category-masonry category-portfolio tag-tag2 tag-tag3 tag-tag1 tag-portfolio tag-video" itemscope itemtype="http://schema.org/Review"> -->

                </div>
                <!-- </div> class="content"> -->

                <?php $this->beginContent('@app/views/layouts/sidebar-recipe.php'); ?>


                <?php $this->endContent(); ?>

            </div>
            <!-- </div> class="content_wrap"> -->
        </div>
        <!-- </.page_content_wrap> -->